apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc-application
spec:
  selector:
    matchLabels:
      app: doc-application
  template:
    metadata:
      labels:
        app: doc-application
    spec:
     containers:
     - name: doc-application
       image: docsearce/doc-application:latest
       imagePullPolicy: Always
       ports:
          - containerPort: 5000
            name: doc-application
