apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc-application
spec:
  selector:
    matchLabels:
      app: dotnet-application
  template:
    metadata:
      labels:
        app: dotnet-application
    spec:
     containers:
     - name: dotnet-application
       image: docsearce/doc-application:latest
       imagePullPolicy: Always
       ports:
          - containerPort: 8080
            name: doc-application
            
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-service
  labels:
    app: dotnet-application
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: dotnet-application
    tier: dotnet-application
  type: LoadBalancer
