apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-deployment
spec:
  selector:
    matchLabels:
      app: dotnetapp
  template:
    metadata:
      labels:
        app: dotnetapp
    spec:
     containers:
     - name: dotnet
       image: docsearce/doc-application:latest
       imagePullPolicy: Always
       ports:
          - containerPort: 80
            
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-service
spec:
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: dotnetapp
