apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc-application
spec:
  selector:
    matchLabels:
      app: doc-application
  template:
    metadata:
      labels:
        app: doc-application
    spec:
     containers:
     - name: doc-application
       image: docsearce/doc-application:latest
       imagePullPolicy: Always
       ports:
          - containerPort: 80
            name: doc-application
            
---
apiVersion: v1
kind: Service
metadata:
  name: doc-application
  labels:
    app: doc-application
spec:
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: doc-application
    tier: doc-application
  type: LoadBalancer
